services:
  bcord:
    stop_signal: SIGTERM
    stop_grace_period: 25s
    environment:
      AUTH_SECRET: "${AUTH_SECRET:-change-me-32+-random-hex}"
      # CHANGE THIS to a random secret (see step 4 to generate)
      WS_SECRET: "b88ec3b517eadde1498dede747683874cf34bf9495db89706ebb4e35ca8fc7f1"
      # set to "1" only in dev; enables /api/token helper endpoint
      ENABLE_DEV_TOKEN: "1"
      S3_ENDPOINT: "play.min.io"
      S3_BUCKET: "bcord-attachments"
      S3_REGION: "us-east-1"
      S3_ACCESS_KEY: "changeme-access"
      S3_SECRET_KEY: "changeme-secret"
      S3_USE_SSL: "1"
      S3_VIRTUAL_HOSTED: "1"
      S3_PRESIGN_TTL_SECONDS: "600"
      S3_PUBLIC_BASE_URL: ""
      DRAIN_CLOSE_AFTER_SECONDS: "20"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/api/ready || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 20s

  postgres:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bcord", "-d", "bcord", "-h", "localhost"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s

  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s

